---
# tasks file for users
  - name: Add the user
    user:
      name: "{{ NAMEUSER }}"
      comment: John Doe

  - name: Add the user  with a bash shell, appending the group 'wheel'
    user:
     name: "{{ NAMEUSER }}"
     shell: /bin/bash
     groups: wheel
     append: yes

  - name: Copy rsa_key
    authorized_key:
      user: "{{ NAMEUSER }}"
      state: present
      key: "{{ ssh_rsa_key }}"
...